from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Shared
# ---------------------------------------------------------------------------

class CopyInput(BaseModel):
    headline: str
    body: str = ""
    cta: str = ""


class Dimensions(BaseModel):
    width: int
    height: int


# ---------------------------------------------------------------------------
# Brand analysis
# ---------------------------------------------------------------------------

class AnalyzeBrandRequest(BaseModel):
    logo_b64: str = Field(description="Logo as data URL or raw base64 PNG")


class AnalyzeBrandResponse(BaseModel):
    primary_color: str
    secondary_color: str
    accent_color: str
    palette: list[str]
    background_suggestion: str = Field(description='"light" or "dark"')
    contrast_color: str = Field(description="#FFFFFF or #000000 for readability on primary")
    suggested_fonts: list[str]


# ---------------------------------------------------------------------------
# Post render (AI-generated template)
# ---------------------------------------------------------------------------

class BrandInput(BaseModel):
    logo_b64: str = Field(description="Logo as data URL or raw base64 PNG")
    primary_color: str = Field(default="#000000", description="Hex color, e.g. #FF6B35")
    secondary_color: str = Field(default="#ffffff", description="Hex color")
    accent_color: str = Field(default="#888888", description="Hex color")
    font_family: str = Field(default="Montserrat", description="Google Font name")


class RenderPostRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    format: str = Field(
        description="Social format: instagram_feed | instagram_story | facebook_post | linkedin_post"
    )
    brand: BrandInput
    post_copy: CopyInput = Field(alias="copy")
    image_prompt: str = Field(description="Prompt for Vertex AI background image generation")
    style_description: str = Field(
        default="profesional, moderno, limpio",
        description='Aesthetic style hint for Claude, e.g. "elegante, premium, minimalista"',
    )


class RenderPostResponse(BaseModel):
    rendered_post: str = Field(description="Rendered PNG as data URL")
    format: str
    dimensions: Dimensions
    html_preview: str = Field(description="Raw HTML generated by Claude (for debugging)")


# ---------------------------------------------------------------------------
# Batch render
# ---------------------------------------------------------------------------

class BatchPostItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    format: str
    post_copy: CopyInput = Field(alias="copy")
    image_prompt: str
    style_description: str = "profesional, moderno, limpio"


class BatchRenderRequest(BaseModel):
    brand: BrandInput
    posts: list[BatchPostItem]


class BatchResultItem(BaseModel):
    index: int
    rendered_post: Optional[str] = None
    format: str
    status: str = Field(description='"success" or "error"')
    error: Optional[str] = None
    # Content fields (populated on success for the intelligent batch)
    headline: Optional[str] = None
    body: Optional[str] = None
    cta: Optional[str] = None
    image_prompt: Optional[str] = None


class BatchRenderResponse(BaseModel):
    results: list[BatchResultItem]


# ---------------------------------------------------------------------------
# Intelligent batch render (LLM-generated copy + image prompts)
# ---------------------------------------------------------------------------

class BrandInputFull(BaseModel):
    """Extended brand input that includes a name for the LLM content generator."""
    name: str = Field(description="Brand / product name fed to the content LLM")
    logo_b64: str = Field(default="", description="Logo as data URL or raw base64 PNG")
    primary_color: str = Field(default="#000000")
    secondary_color: str = Field(default="#ffffff")
    accent_color: str = Field(default="#888888")
    contrast_color: str = Field(default="#ffffff")
    font_family: str = Field(default="Montserrat")


class CampaignInput(BaseModel):
    description: str = Field(description="What the product is and the campaign goal")
    tone: str = Field(
        default="profesional y directo",
        description='Desired tone, e.g. "divertido y casual" or "elegante y premium"',
    )
    extras: str = Field(
        default="",
        description="Hashtags, slogans, or any extra notes for the LLM",
    )


class PostConfigItem(BaseModel):
    platform: str = Field(default="instagram")
    format: str = Field(
        description="instagram_feed | instagram_story | facebook_post | linkedin_post"
    )


class SmartBatchRenderRequest(BaseModel):
    """New intelligent batch request — the LLM generates copy + image prompts."""
    brand: BrandInputFull
    campaign: CampaignInput
    product_images: list[str] = Field(
        default=[],
        description="List of product photos as base64 data URLs. "
        "When provided, Flux Kontext Pro is used for image-to-image generation.",
    )
    include_logo_in_image: bool = Field(
        default=False,
        description="When True, the logo is integrated into the generated scene "
        "via Nano Banana 2 Edit (2-pass pipeline). When False, no logo in image.",
    )
    include_text_in_image: bool = Field(
        default=False,
        description="When True, Nano Banana 2 Edit renders the headline and CTA "
        "as pixel-perfect text directly on the image.",
    )
    logo_analysis: dict | None = Field(
        default=None,
        description="Vision analysis of the logo from /brand/analyze-vision",
    )
    product_analysis: dict | None = Field(
        default=None,
        description="Vision analysis of the product from /product/analyze",
    )
    posts_config: list[PostConfigItem] = Field(
        min_length=1, description="One entry per post to generate"
    )
    language: str = Field(
        default="auto",
        pattern="^(es|en|auto)$",
        description='Content language: "es" (Spanish), "en" (English), or "auto" (detect).',
    )
    chat_messages: list[dict] | None = Field(
        default=None,
        description="Recent chat messages for language auto-detection context.",
    )
    draft_id: str | None = Field(
        default=None,
        description="If provided, links the job to this parrilla_draft and tracks its lifecycle.",
    )


class SmartBatchRenderResponse(BaseModel):
    results: list[BatchResultItem]


# ---------------------------------------------------------------------------
# Async generation (job-based)
# ---------------------------------------------------------------------------

class GenerateResponse(BaseModel):
    job_id: str
    total_posts: int
    status: str = "processing"


class JobStatusResponse(BaseModel):
    job: dict
    posts: list[dict]


# ---------------------------------------------------------------------------
# Static templates list (backward-compat)
# ---------------------------------------------------------------------------

class TemplateMeta(BaseModel):
    id: str
    name: str
    description: str
    preview_thumbnail: str
    supported_formats: list[str]


class TemplatesListResponse(BaseModel):
    templates: list[TemplateMeta]


# ---------------------------------------------------------------------------
# Video generation
# ---------------------------------------------------------------------------

class VideoGenerateRequest(BaseModel):
    duration: str = Field(default="5", description='Video duration: "5" or "10" seconds')
    aspect_ratio: str = Field(
        default="",
        description="Override aspect ratio (defaults to post format ratio)",
    )


class VideoGenerateResponse(BaseModel):
    post_id: str
    video_status: str = "processing"


class VideoStatusResponse(BaseModel):
    post_id: str
    video_status: Optional[str] = "none"
    video_url: Optional[str] = None
    video_error: Optional[str] = None
    motion_prompt: Optional[str] = None


# ---------------------------------------------------------------------------
# Post edit chat
# ---------------------------------------------------------------------------

class EditChatRequest(BaseModel):
    user_message: str = Field(default="", description="Free-form edit instruction")
    quick_action: Optional[str] = Field(
        default=None,
        description="Predefined quick action: more_vibrant, different_angle, "
        "more_minimalist, change_background, more_editorial, better_lighting, "
        "closer_shot, change_typography",
    )


class EditChatResponse(BaseModel):
    ai_response: str
    change_scope: str
    version_id: str
    status: str = "regenerating"


class EditChatHistoryResponse(BaseModel):
    messages: list[dict]


class PostVersionItem(BaseModel):
    id: str
    version_number: int
    rendered_image_url: Optional[str] = None
    is_current: bool
    user_message: Optional[str] = None
    change_scope: Optional[str] = None
    created_at: str


class PostVersionsResponse(BaseModel):
    versions: list[PostVersionItem]


class RestoreVersionResponse(BaseModel):
    post_id: str
    restored_version: int
    status: str = "restored"


# ---------------------------------------------------------------------------
# Approve & image generation (two-phase pipeline)
# ---------------------------------------------------------------------------

class ApproveAndGenerateImageResponse(BaseModel):
    post_id: str
    approval_status: str = "approved"
    image_status: str = "generating"


class GenerateAllApprovedImagesResponse(BaseModel):
    count: int
    status: str = "generating_images"
    message: str = ""

